### ISSUE TITLE
带有横竖屏切换的demo能给一份吗

### ISSUE THREAD

**Issue by 1119093254** [william198824/JTCameraViewDemo#1]
部分机型有bug没事，麻烦发我一下邮箱吧  602742141@qq.com     谢谢

**Comment by vee-zhang** [comment]
横竖屏切换的功能的相关代码没有留存，但我当时做的时候，是参考google官方的CameraView来做的，所以你可以去看CameraView的源码即可。

**Comment by vee-zhang** [comment]
第二版已经补全了功能，包含横竖屏切换，可以直接看源码。
